### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by jezdez** [not-kennethreitz/humble#2]
Not sure what causes this, traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/humble", line 9, in <module>
    load_entry_point('humble==0.1.1', 'console_scripts', 'humble')()
  File "/Library/Python/2.6/site-packages/humble/cli.py", line 57, in start
    '{} followers'.format(str(user.followers_count)),
ValueError: zero length field name in format
```

**Comment by ojii** [comment]
getting the same

**Comment by kennethreitz** [comment]
Thanks for the report. I just pushed an update (v0.1.2) that adds support for Python 2.5 and 2.6, which fixes this problem. 

   $ pip install humble --upgrade

**Comment by ojii** [comment]
yay works:
    jonas@jonas-mbp:~/workspace/django-cms.org$ humble ojii
    ojii - 45 followers - 49 public repositories
    django-classy-tags                     116 watchers   4 forks  
    django-multilingual-ng                 58 watchers    15 forks  
    django-mailchimp                       54 watchers    7 forks  
    django-sekizai                         31 watchers    2 forks  
    django-admin-filters                   21 watchers    2 forks  
    django-csv-export                      15 watchers    6 forks  
    django-demo                            14 watchers    1 fork  
    django-server-manager                  12 watchers    1 fork  
    project-nani                           12 watchers    3 forks  
    django-login-as                        11 watchers    1 fork  
    django-cms                             6 watchers     2 forks    (FORK)  
    django-dashboard                       5 watchers     1 fork  
    django-cms-jplayer                     4 watchers     1 fork  
    django-utils                           4 watchers     2 forks  
    django-load                            4 watchers     1 fork  
    django-sitepermissions                 3 watchers     2 forks  
    django-birthday                        3 watchers     1 fork  
    django-localcrawler                    3 watchers     1 fork  
    alert-grid                             3 watchers     2 forks  
    readthedocs.org                        3 watchers     0 fork     (FORK)  
    django-cms-epio-quickstart             3 watchers     2 forks  
    cmsplugin-rst                          3 watchers     1 fork  
    django-rat                             2 watchers     1 fork  
    ojii                                   2 watchers     1 fork  
    django-cms-quickstart                  2 watchers     1 fork  
    django-shop                            2 watchers     0 fork     (FORK)  
    patu                                   1 watcher      1 fork     (FORK)  
    django-css                             1 watcher      1 fork     (FORK)  
    cmsplugin-filer                        1 watcher      1 fork     (FORK)  
    django-filer                           1 watcher      1 fork     (FORK)  
    django                                 1 watcher      1 fork     (FORK)  
    pony_barn                              1 watcher      1 fork     (FORK)  
    howbig                                 1 watcher      1 fork  
    django-uni-form                        1 watcher      1 fork     (FORK)  
    djangopackages                         1 watcher      1 fork     (FORK)  
    django-hudson                          1 watcher      0 fork     (FORK)  
    python-github2                         1 watcher      0 fork     (FORK)  
    django-fixture-shell                   1 watcher      1 fork  
    cmsplugin-facebook                     1 watcher      0 fork     (FORK)  
    django-cms-html5-1140px-boilerplate    1 watcher      0 fork     (FORK)  
    django-kong                            1 watcher      0 fork     (FORK)  
    cmsplugin-blog                         1 watcher      0 fork     (FORK)  
    django-newcache                        1 watcher      0 fork     (FORK)  
    cmsplugin-placeholder-gallery          1 watcher      1 fork  
    django-tablib                          1 watcher      0 fork     (FORK)  
    djangobench                            1 watcher      0 fork     (FORK)  
    django-rulez                           1 watcher      0 fork     (FORK)  
    django-shop-simplecategories           1 watcher      0 fork     (FORK)  
    django-shop-simplevariations           1 watcher      0 fork     (FORK)

**Comment by kennethreitz** [comment]
:cake:
